name: FinTrack QA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Automation/requirements.txt
      - name: Run API tests
        run: pytest Automation/api_tests -q --junitxml=reports/api_tests.xml
      - name: Run UI tests
        run: pytest Automation/tests -q --junitxml=reports/ui_tests.xml
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
